-- Pre-Alembic baseline schema.
--
-- 521d1b9ef974_initial_migration.py is not an initial migration: it is an
-- autogenerated diff against a hand-created Supabase schema that Alembic has never
-- been able to build. Its upgrade() opens with `ALTER TABLE curation_jobs ADD COLUMN
-- ...`, so `alembic upgrade head` against an empty database fails on the first
-- statement. Nobody had noticed, because nobody had ever run the chain from scratch.
--
-- This file reconstructs that starting point so gate 8.4 can run the real migrations
-- against real Postgres. Every column here is one the chain either drops, alters, or
-- silently depends on — read 521d1b9ef974's upgrade() alongside it.
--
-- TEST FIXTURE ONLY. Never run this against a real database.

CREATE TABLE research_jobs (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    status            text,
    video_topic       text,
    research_summary  text,
    research_depth    text,
    created_at        timestamptz DEFAULT now(),
    updated_at        timestamptz
);

CREATE TABLE research_videos (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    job_id       uuid,
    video_id     text,
    title        text,
    description  text,
    metadata     jsonb,
    view_count   bigint,
    transcript   text,
    published_at timestamptz,
    created_at   timestamptz DEFAULT now(),
    CONSTRAINT research_videos_job_id_fkey FOREIGN KEY (job_id) REFERENCES research_jobs (id)
);

CREATE TABLE curation_jobs (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    research_job_id uuid REFERENCES research_jobs (id),
    status          text,
    curation_notes  text,
    selected_clips  jsonb,
    created_at      timestamptz DEFAULT now(),
    updated_at      timestamptz
);

CREATE TABLE production_jobs (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    curation_job_id uuid REFERENCES curation_jobs (id),
    status          text,
    title           text,
    output_url      text,
    style           text,
    created_at      timestamptz DEFAULT now(),
    updated_at      timestamptz
);

CREATE TABLE production_scenes (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    production_job_id uuid,
    scene_number      integer NOT NULL,
    media_url         text,
    visual_prompt     text,
    audio_prompt      text,
    status            text,
    duration          numeric,
    created_at        timestamptz DEFAULT now(),
    CONSTRAINT production_scenes_production_job_id_fkey
        FOREIGN KEY (production_job_id) REFERENCES production_jobs (id)
);

CREATE TABLE production_tracks (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    production_job_id uuid,
    track_type        text,
    provider          text,
    content_url       text,
    metadata          jsonb,
    duration          numeric,
    created_at        timestamptz DEFAULT now(),
    CONSTRAINT production_tracks_production_job_id_fkey
        FOREIGN KEY (production_job_id) REFERENCES production_jobs (id)
);

CREATE TABLE system_config (
    key        text PRIMARY KEY,
    value      jsonb,
    updated_at timestamptz DEFAULT now()
);
