import axios from 'axios';

const API_BASE_URL = 'http://localhost:8000/api/curation';

/** Scene as generated by Claude (new schema from claude_service.py) */
export interface StoryboardScene {
    // New Claude schema
    scene_index?: number;
    narration?: string;
    visual_prompt: string;
    pacing?: string;
    duration?: number;
    // Legacy / extended fields from older curation jobs
    scene_number?: number;
    description?: string;
    motion_prompt?: string;
    kling_mode?: 'std' | 'pro';
    negative_prompt?: string;
}

export interface CreativeBrief {
    title: string;
    hook: string;
    narrative_goal: string;
    music_mood: string;
    color_palette: string[];
    // Supports both key variants
    storyboard?: StoryboardScene[];
    scenes?: StoryboardScene[];
    error?: string;
}

export interface CurationJob {
    id: string;
    research_job_id: string;
    status: 'pending' | 'generating_brief' | 'completed' | 'error' | 'failed';
    creative_brief?: CreativeBrief;
    user_approved_brief?: CreativeBrief;
    num_scenes?: number;
    created_at?: string | null;
    approved_at?: string | null;
}

/** Normalise a brief to always have a `storyboard` array regardless of which key the backend used */
export function normaliseBrief(brief: CreativeBrief): CreativeBrief {
    return {
        ...brief,
        storyboard: brief.storyboard ?? brief.scenes ?? [],
    };
}

export const curationService = {
    startCuration: async (researchJobId: string, selectedVideoIds?: string[]): Promise<CurationJob> => {
        const response = await axios.post(`${API_BASE_URL}/start`, {
            research_job_id: researchJobId,
            selected_video_ids: selectedVideoIds,
        });
        return response.data;
    },

    listJobs: async (): Promise<CurationJob[]> => {
        const response = await axios.get(`${API_BASE_URL}/`);
        return response.data;
    },

    getJob: async (jobId: string): Promise<CurationJob> => {
        const response = await axios.get(`${API_BASE_URL}/${jobId}`);
        return response.data;
    },
};
