"""Initial migration

Revision ID: 521d1b9ef974
Revises: 
Create Date: 2026-02-26 14:28:35.112230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '521d1b9ef974'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curation_jobs', sa.Column('selected_video_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('curation_jobs', sa.Column('creative_brief', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('curation_jobs', sa.Column('user_approved_brief', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('curation_jobs', sa.Column('num_scenes', sa.Integer(), nullable=True))
    op.add_column('curation_jobs', sa.Column('image_model', sa.String(length=50), nullable=True))
    op.add_column('curation_jobs', sa.Column('video_model', sa.String(length=50), nullable=True))
    op.add_column('curation_jobs', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('curation_jobs', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=True)
    op.drop_column('curation_jobs', 'curation_notes')
    op.drop_column('curation_jobs', 'selected_clips')
    op.drop_column('curation_jobs', 'updated_at')
    op.add_column('production_jobs', sa.Column('job_dir', sa.Text(), nullable=True))
    op.add_column('production_jobs', sa.Column('num_tracks', sa.Integer(), nullable=True))
    op.add_column('production_jobs', sa.Column('num_scenes', sa.Integer(), nullable=True))
    op.add_column('production_jobs', sa.Column('concatenated_audio_path', sa.Text(), nullable=True))
    op.add_column('production_jobs', sa.Column('beat_timestamps', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('production_jobs', sa.Column('assembled_video_path', sa.Text(), nullable=True))
    op.add_column('production_jobs', sa.Column('final_video_path', sa.Text(), nullable=True))
    op.add_column('production_jobs', sa.Column('youtube_video_id', sa.Text(), nullable=True))
    op.add_column('production_jobs', sa.Column('youtube_title', sa.Text(), nullable=True))
    op.add_column('production_jobs', sa.Column('youtube_description', sa.Text(), nullable=True))
    op.add_column('production_jobs', sa.Column('youtube_hashtags', sa.Text(), nullable=True))
    op.add_column('production_jobs', sa.Column('total_duration_sec', sa.Numeric(), nullable=True))
    op.add_column('production_jobs', sa.Column('file_size_bytes', sa.BigInteger(), nullable=True))
    op.add_column('production_jobs', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('production_jobs', sa.Column('celery_task_id', sa.String(), nullable=True))
    op.add_column('production_jobs', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('production_jobs', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               nullable=True)
    op.drop_column('production_jobs', 'title')
    op.drop_column('production_jobs', 'output_url')
    op.drop_column('production_jobs', 'updated_at')
    op.drop_column('production_jobs', 'style')
    op.add_column('production_scenes', sa.Column('job_id', sa.UUID(), nullable=True))
    op.add_column('production_scenes', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('production_scenes', sa.Column('image_prompt', sa.Text(), nullable=True))
    op.add_column('production_scenes', sa.Column('image_model', sa.String(length=50), nullable=True))
    op.add_column('production_scenes', sa.Column('image_url', sa.Text(), nullable=True))
    op.add_column('production_scenes', sa.Column('local_image_path', sa.Text(), nullable=True))
    op.add_column('production_scenes', sa.Column('animation_method', sa.String(length=30), nullable=True))
    op.add_column('production_scenes', sa.Column('animation_model', sa.String(length=50), nullable=True))
    op.add_column('production_scenes', sa.Column('animation_decision', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('production_scenes', sa.Column('motion_prompt', sa.Text(), nullable=True))
    op.add_column('production_scenes', sa.Column('cometapi_task_id', sa.String(), nullable=True))
    op.add_column('production_scenes', sa.Column('animation_status', sa.String(length=20), nullable=True))
    op.add_column('production_scenes', sa.Column('local_video_path', sa.Text(), nullable=True))
    op.add_column('production_scenes', sa.Column('duration_seconds', sa.Numeric(), nullable=True))
    op.add_column('production_scenes', sa.Column('beat_cut_start_sec', sa.Numeric(), nullable=True))
    op.add_column('production_scenes', sa.Column('beat_cut_end_sec', sa.Numeric(), nullable=True))
    op.alter_column('production_scenes', 'scene_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('production_scenes_production_job_id_fkey'), 'production_scenes', type_='foreignkey')
    op.create_foreign_key(None, 'production_scenes', 'production_jobs', ['job_id'], ['id'])
    op.drop_column('production_scenes', 'media_url')
    op.drop_column('production_scenes', 'production_job_id')
    op.drop_column('production_scenes', 'visual_prompt')
    op.drop_column('production_scenes', 'audio_prompt')
    op.drop_column('production_scenes', 'status')
    op.drop_column('production_scenes', 'duration')
    op.add_column('production_tracks', sa.Column('job_id', sa.UUID(), nullable=True))
    op.add_column('production_tracks', sa.Column('track_number', sa.Integer(), nullable=True))
    op.add_column('production_tracks', sa.Column('song_prompt', sa.Text(), nullable=True))
    op.add_column('production_tracks', sa.Column('suno_task_id', sa.String(), nullable=True))
    op.add_column('production_tracks', sa.Column('suno_status', sa.String(length=20), nullable=True))
    op.add_column('production_tracks', sa.Column('title', sa.Text(), nullable=True))
    op.add_column('production_tracks', sa.Column('duration_seconds', sa.Numeric(), nullable=True))
    op.add_column('production_tracks', sa.Column('audio_url', sa.Text(), nullable=True))
    op.add_column('production_tracks', sa.Column('local_audio_path', sa.Text(), nullable=True))
    op.add_column('production_tracks', sa.Column('error_message', sa.Text(), nullable=True))
    op.drop_constraint(op.f('production_tracks_production_job_id_fkey'), 'production_tracks', type_='foreignkey')
    op.create_foreign_key(None, 'production_tracks', 'production_jobs', ['job_id'], ['id'])
    op.drop_column('production_tracks', 'track_type')
    op.drop_column('production_tracks', 'provider')
    op.drop_column('production_tracks', 'production_job_id')
    op.drop_column('production_tracks', 'content_url')
    op.drop_column('production_tracks', 'metadata')
    op.drop_column('production_tracks', 'duration')
    op.add_column('research_jobs', sa.Column('genre_topic', sa.Text(), nullable=False))
    op.add_column('research_jobs', sa.Column('expanded_queries', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('research_jobs', sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('research_jobs', sa.Column('top_n', sa.Integer(), nullable=True))
    op.add_column('research_jobs', sa.Column('gemini_model', sa.String(length=100), nullable=True))
    op.add_column('research_jobs', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('research_jobs', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('research_jobs', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=True)
    op.drop_column('research_jobs', 'video_topic')
    op.drop_column('research_jobs', 'research_summary')
    op.drop_column('research_jobs', 'research_depth')
    op.drop_column('research_jobs', 'updated_at')
    op.add_column('research_videos', sa.Column('channel', sa.String(), nullable=True))
    op.add_column('research_videos', sa.Column('views', sa.BigInteger(), nullable=True))
    op.add_column('research_videos', sa.Column('likes', sa.BigInteger(), nullable=True))
    op.add_column('research_videos', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    op.add_column('research_videos', sa.Column('thumbnail_url', sa.Text(), nullable=True))
    op.add_column('research_videos', sa.Column('url', sa.Text(), nullable=True))
    op.add_column('research_videos', sa.Column('relevance_score', sa.Integer(), nullable=True))
    op.add_column('research_videos', sa.Column('gemini_reasoning', sa.Text(), nullable=True))
    op.add_column('research_videos', sa.Column('selected_for_curation', sa.Boolean(), nullable=True))
    op.alter_column('research_videos', 'video_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=True)
    op.drop_constraint(op.f('research_videos_job_id_fkey'), 'research_videos', type_='foreignkey')
    op.create_foreign_key(None, 'research_videos', 'research_jobs', ['job_id'], ['id'])
    op.drop_column('research_videos', 'metadata')
    op.drop_column('research_videos', 'view_count')
    op.drop_column('research_videos', 'transcript')
    op.add_column('system_config', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('system_config', sa.Column('is_secret', sa.Boolean(), nullable=True))
    op.alter_column('system_config', 'key',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('system_config', 'value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_config', 'value',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('system_config', 'key',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('system_config', 'is_secret')
    op.drop_column('system_config', 'description')
    op.add_column('research_videos', sa.Column('transcript', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('research_videos', sa.Column('view_count', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('research_videos', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'research_videos', type_='foreignkey')
    op.create_foreign_key(op.f('research_videos_job_id_fkey'), 'research_videos', 'research_jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.alter_column('research_videos', 'video_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_column('research_videos', 'selected_for_curation')
    op.drop_column('research_videos', 'gemini_reasoning')
    op.drop_column('research_videos', 'relevance_score')
    op.drop_column('research_videos', 'url')
    op.drop_column('research_videos', 'thumbnail_url')
    op.drop_column('research_videos', 'duration_seconds')
    op.drop_column('research_videos', 'likes')
    op.drop_column('research_videos', 'views')
    op.drop_column('research_videos', 'channel')
    op.add_column('research_jobs', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('research_jobs', sa.Column('research_depth', sa.TEXT(), server_default=sa.text("'standard'::text"), autoincrement=False, nullable=True))
    op.add_column('research_jobs', sa.Column('research_summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('research_jobs', sa.Column('video_topic', sa.TEXT(), autoincrement=False, nullable=False))
    op.alter_column('research_jobs', 'status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_column('research_jobs', 'completed_at')
    op.drop_column('research_jobs', 'error_message')
    op.drop_column('research_jobs', 'gemini_model')
    op.drop_column('research_jobs', 'top_n')
    op.drop_column('research_jobs', 'filters')
    op.drop_column('research_jobs', 'expanded_queries')
    op.drop_column('research_jobs', 'genre_topic')
    op.add_column('production_tracks', sa.Column('duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('production_tracks', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('production_tracks', sa.Column('content_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('production_tracks', sa.Column('production_job_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('production_tracks', sa.Column('provider', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('production_tracks', sa.Column('track_type', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'production_tracks', type_='foreignkey')
    op.create_foreign_key(op.f('production_tracks_production_job_id_fkey'), 'production_tracks', 'production_jobs', ['production_job_id'], ['id'], ondelete='CASCADE')
    op.drop_column('production_tracks', 'error_message')
    op.drop_column('production_tracks', 'local_audio_path')
    op.drop_column('production_tracks', 'audio_url')
    op.drop_column('production_tracks', 'duration_seconds')
    op.drop_column('production_tracks', 'title')
    op.drop_column('production_tracks', 'suno_status')
    op.drop_column('production_tracks', 'suno_task_id')
    op.drop_column('production_tracks', 'song_prompt')
    op.drop_column('production_tracks', 'track_number')
    op.drop_column('production_tracks', 'job_id')
    op.add_column('production_scenes', sa.Column('duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('production_scenes', sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('production_scenes', sa.Column('audio_prompt', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('production_scenes', sa.Column('visual_prompt', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('production_scenes', sa.Column('production_job_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('production_scenes', sa.Column('media_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'production_scenes', type_='foreignkey')
    op.create_foreign_key(op.f('production_scenes_production_job_id_fkey'), 'production_scenes', 'production_jobs', ['production_job_id'], ['id'], ondelete='CASCADE')
    op.alter_column('production_scenes', 'scene_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('production_scenes', 'beat_cut_end_sec')
    op.drop_column('production_scenes', 'beat_cut_start_sec')
    op.drop_column('production_scenes', 'duration_seconds')
    op.drop_column('production_scenes', 'local_video_path')
    op.drop_column('production_scenes', 'animation_status')
    op.drop_column('production_scenes', 'cometapi_task_id')
    op.drop_column('production_scenes', 'motion_prompt')
    op.drop_column('production_scenes', 'animation_decision')
    op.drop_column('production_scenes', 'animation_model')
    op.drop_column('production_scenes', 'animation_method')
    op.drop_column('production_scenes', 'local_image_path')
    op.drop_column('production_scenes', 'image_url')
    op.drop_column('production_scenes', 'image_model')
    op.drop_column('production_scenes', 'image_prompt')
    op.drop_column('production_scenes', 'description')
    op.drop_column('production_scenes', 'job_id')
    op.add_column('production_jobs', sa.Column('style', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('production_jobs', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('production_jobs', sa.Column('output_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('production_jobs', sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False))
    op.alter_column('production_jobs', 'status',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_column('production_jobs', 'published_at')
    op.drop_column('production_jobs', 'celery_task_id')
    op.drop_column('production_jobs', 'error_message')
    op.drop_column('production_jobs', 'file_size_bytes')
    op.drop_column('production_jobs', 'total_duration_sec')
    op.drop_column('production_jobs', 'youtube_hashtags')
    op.drop_column('production_jobs', 'youtube_description')
    op.drop_column('production_jobs', 'youtube_title')
    op.drop_column('production_jobs', 'youtube_video_id')
    op.drop_column('production_jobs', 'final_video_path')
    op.drop_column('production_jobs', 'assembled_video_path')
    op.drop_column('production_jobs', 'beat_timestamps')
    op.drop_column('production_jobs', 'concatenated_audio_path')
    op.drop_column('production_jobs', 'num_scenes')
    op.drop_column('production_jobs', 'num_tracks')
    op.drop_column('production_jobs', 'job_dir')
    op.add_column('curation_jobs', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('curation_jobs', sa.Column('selected_clips', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('curation_jobs', sa.Column('curation_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('curation_jobs', 'status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_column('curation_jobs', 'approved_at')
    op.drop_column('curation_jobs', 'video_model')
    op.drop_column('curation_jobs', 'image_model')
    op.drop_column('curation_jobs', 'num_scenes')
    op.drop_column('curation_jobs', 'user_approved_brief')
    op.drop_column('curation_jobs', 'creative_brief')
    op.drop_column('curation_jobs', 'selected_video_ids')
    # ### end Alembic commands ###
