"""stage2_schema_alignment

Revision ID: 7f4bf2748828
Revises: a2b3c4d5e6f7
Create Date: 2026-04-06 22:52:58.764975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f4bf2748828'
down_revision: Union[str, Sequence[str], None] = 'a2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curation_jobs', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('production_jobs', sa.Column('audio_duration_sec', sa.Numeric(), nullable=True))
    op.add_column('production_jobs', sa.Column('beat_interval_sec', sa.Numeric(), nullable=True))
    op.add_column('production_jobs', sa.Column('tempo_bpm', sa.Numeric(), nullable=True))
    op.add_column('production_scenes', sa.Column('lyric_or_timestamp', sa.Text(), nullable=True))
    op.add_column('production_scenes', sa.Column('target_duration_sec', sa.Numeric(), nullable=True))
    op.add_column('production_scenes', sa.Column('kling_model', sa.String(length=30), nullable=True))
    op.add_column('production_scenes', sa.Column('kling_mode', sa.String(length=10), nullable=True))
    op.add_column('production_scenes', sa.Column('image_tail_scene_id', sa.UUID(), nullable=True))
    op.add_column('production_scenes', sa.Column('image_b64_path', sa.Text(), nullable=True))
    op.add_column('production_scenes', sa.Column('negative_prompt', sa.Text(), nullable=True))
    op.add_column('production_scenes', sa.Column('kling_request_dur', sa.Integer(), nullable=True))
    op.add_column('production_scenes', sa.Column('kling_task_id', sa.String(length=255), nullable=True))
    op.add_column('production_scenes', sa.Column('kling_status', sa.String(length=20), nullable=True))
    op.add_column('production_scenes', sa.Column('raw_video_url', sa.Text(), nullable=True))
    op.add_column('production_scenes', sa.Column('raw_video_path', sa.Text(), nullable=True))
    op.add_column('production_scenes', sa.Column('beat_start_sec', sa.Numeric(), nullable=True))
    op.add_column('production_scenes', sa.Column('beat_end_sec', sa.Numeric(), nullable=True))
    op.add_column('production_scenes', sa.Column('beat_duration_sec', sa.Numeric(), nullable=True))
    op.add_column('production_scenes', sa.Column('beat_drift_ms', sa.Numeric(), nullable=True))
    op.add_column('production_scenes', sa.Column('error_message', sa.Text(), nullable=True))
    op.alter_column('production_scenes', 'scene_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'production_scenes', ['job_id', 'scene_number'])
    op.create_foreign_key(None, 'production_scenes', 'production_scenes', ['image_tail_scene_id'], ['id'])
    op.drop_column('production_scenes', 'beat_cut_end_sec')
    op.drop_column('production_scenes', 'beat_cut_start_sec')
    op.drop_column('production_scenes', 'duration_seconds')
    op.drop_column('production_scenes', 'cometapi_task_id')
    op.drop_column('production_scenes', 'animation_status')
    op.drop_column('production_scenes', 'animation_model')
    op.drop_column('production_scenes', 'animation_decision')
    op.alter_column('production_tracks', 'track_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'production_tracks', ['job_id', 'track_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'production_tracks', type_='unique')
    op.alter_column('production_tracks', 'track_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('production_scenes', sa.Column('animation_decision', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('production_scenes', sa.Column('animation_model', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('production_scenes', sa.Column('animation_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('production_scenes', sa.Column('cometapi_task_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('production_scenes', sa.Column('duration_seconds', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('production_scenes', sa.Column('beat_cut_start_sec', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('production_scenes', sa.Column('beat_cut_end_sec', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'production_scenes', type_='foreignkey')
    op.drop_constraint(None, 'production_scenes', type_='unique')
    op.alter_column('production_scenes', 'scene_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('production_scenes', 'error_message')
    op.drop_column('production_scenes', 'beat_drift_ms')
    op.drop_column('production_scenes', 'beat_duration_sec')
    op.drop_column('production_scenes', 'beat_end_sec')
    op.drop_column('production_scenes', 'beat_start_sec')
    op.drop_column('production_scenes', 'raw_video_path')
    op.drop_column('production_scenes', 'raw_video_url')
    op.drop_column('production_scenes', 'kling_status')
    op.drop_column('production_scenes', 'kling_task_id')
    op.drop_column('production_scenes', 'kling_request_dur')
    op.drop_column('production_scenes', 'negative_prompt')
    op.drop_column('production_scenes', 'image_b64_path')
    op.drop_column('production_scenes', 'image_tail_scene_id')
    op.drop_column('production_scenes', 'kling_mode')
    op.drop_column('production_scenes', 'kling_model')
    op.drop_column('production_scenes', 'target_duration_sec')
    op.drop_column('production_scenes', 'lyric_or_timestamp')
    op.drop_column('production_jobs', 'tempo_bpm')
    op.drop_column('production_jobs', 'beat_interval_sec')
    op.drop_column('production_jobs', 'audio_duration_sec')
    op.drop_column('curation_jobs', 'error_message')
    # ### end Alembic commands ###
