#!/usr/bin/env python3
"""
Regenerate skills/general/claude-movie-director/SKILLS_INDEX.md from the actual tree.

The index used to be hand-maintained and drifted: it advertised eight skills under
paths that no longer existed. Run this after adding, renaming or removing a skill:

    python3 ops/regen_skills_index.py
"""
from __future__ import annotations

import re
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SKILLS_ROOT = REPO_ROOT / "skills"
INDEX_PATH = SKILLS_ROOT / "general" / "claude-movie-director" / "SKILLS_INDEX.md"


def read_frontmatter(skill_md: Path) -> dict[str, str]:
    """Pull `name` and `description` out of a SKILL.md YAML frontmatter block."""
    text = skill_md.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return {}
    parts = text.split("---", 2)
    if len(parts) < 3:
        return {}

    fields: dict[str, str] = {}
    current: str | None = None
    for line in parts[1].strip().splitlines():
        if not line.startswith(" ") and ":" in line:
            key, val = line.split(":", 1)
            current = key.strip()
            val = val.strip()
            fields[current] = "" if val in (">-", ">", "|-", "|") else val
            if fields[current]:
                current = None
        elif current and line.startswith("  "):
            existing = fields.get(current, "")
            fields[current] = (existing + " " if existing else "") + line.strip()
    return fields


def collect() -> list[tuple[str, str, str, str]]:
    """Return (category, slug, name, description) for every SKILL.md on disk."""
    rows = []
    for skill_md in sorted(SKILLS_ROOT.glob("*/*/SKILL.md")):
        directory = skill_md.parent
        category = directory.parent.name
        fm = read_frontmatter(skill_md)
        name = fm.get("name") or directory.name
        description = re.sub(r"\s+", " ", fm.get("description", "")).strip()
        if len(description) > 220:
            description = description[:217].rstrip() + "..."
        rows.append((category, directory.name, name, description))
    return rows


def render(rows: list[tuple[str, str, str, str]]) -> str:
    lines = [
        "# Claude Movie Director — Skills Index",
        "",
        "> Generated by `ops/regen_skills_index.py` — do not edit by hand.",
        f"> Last generated: {date.today().isoformat()} | {len(rows)} skills on disk.",
        "",
        "Skills live at `skills/{category}/{directory}/SKILL.md`. The loader",
        "(`backend/app/services/skill_loader_service.py`) resolves a slug against the flat",
        "layout first, then `skills/*/<slug>/`, then `skills/*/<slug>*/` so versioned",
        "directories such as `seedance2-director-v2` still answer to `seedance2-director`.",
        "",
    ]

    for category in sorted({r[0] for r in rows}):
        lines.append(f"## {category}")
        lines.append("")
        lines.append("| Skill | Directory | Purpose |")
        lines.append("|---|---|---|")
        for _, directory, name, description in [r for r in rows if r[0] == category]:
            lines.append(f"| **{name}** | `{directory}` | {description or '—'} |")
        lines.append("")

    return "\n".join(lines) + "\n"


def main() -> None:
    rows = collect()
    INDEX_PATH.write_text(render(rows), encoding="utf-8")
    print(f"Wrote {INDEX_PATH.relative_to(REPO_ROOT)} — {len(rows)} skills")


if __name__ == "__main__":
    main()
